# see https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file
[build]
  publish = "dist"
  command = "nuxt build && nuxt export"
#  functions = "project/functions/"
[environment]
  NODE_VERSION = "12.*"
  FIREBASE_APIKEY="AIzaSyCIfQPTBbAWN0V64gMP-3fivC5JUPPahWM"
  FIREBASE_AUTHDOMAIN="chatbox2020-26423.firebaseapp.com"
  FIREBASE_DATABASEURL="https://chatbox2020-26423.firebaseio.com"
  FIREBASE_PROJECTID="chatbox2020-26423"
  FIREBASE_STORAGEBUCKET="chatbox2020-26423.appspot.com"
  FIREBASE_MESSAGESENDERID="242233420493"
  FIREBASE_APPID="1:242233420493:web:3c9af8562c50efc7211784"
  FIREBASE_MEASUREMENTID="G-HK4N2HNG5Q"

[context.branch-deploy.environment]
  NODE_ENV = "development"
#
#[context.deploy-preview.environment]
#  NODE_ENV = "production"
#
## Branch Deploy context: all deploys that are not from a pull/merge request or
## from the Production branch will inherit these settings.
#[context.branch-deploy]
#  command = "echo branch"
#
#[context.dev]
#  command = "echo 'staging'"
#  base = "staging"